### ISSUE TITLE
Network Issues

### ISSUE THREAD

**Issue by jeffmikels** [CharlesCCC/Asus-Prime-Z490-A-OpenCore-Hackintosh#2]
I just installed Monterey using this EFI on the same motherboard with 32GB RAM, and a RX580. I loaded the default Optimized BIOS settings. It went well. However, I am using the onboard network adapter instead of WiFi.

During initial setup, whenever the computer tried to access the network, it would immediately reboot.

By disconnecting the network cable and skipping network setup, the setup continued without a problem and I am now at a fully working Monterey desktop... minus the network.

Are you experiencing any network problems?

**Comment by CharlesCCC** [comment]
@jeffmikels hi Jeff, Yes, I had similar experience/issue before, I believe it is caused by this [change](https://github.com/CharlesCCC/Asus-Prime-Z490-A-OpenCore-Hackintosh/commit/c620ff92c923df45db17b754d2461d181e26b9a0#diff-18ce8f2001c3c18075dbf54219a44cbfbc93fc79f0f2ab519305ed1bcd16112eL931)

You might try add the `dk.e1000=0` flag back, but it could cause you not able to boot into the system.
